---
- name: Update apt cache if required
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: "Installing vital packages"
  apt: pkg={{item}} state=present
  with_items:
  - build-essential
  - libpcre++-dev
  - unzip
  - git-core
  - vim
  - openssl
  - libssl-dev
  sudo: yes