---
- name: "Installing vital packages"
  apt: pkg={{item}} state=latest update-cache=yes
  with_items:
  - build-essential
  - libpcre++-dev
  - unzip
  - git-core
  - vim
  - openssl
  - libssl-dev
  sudo: yes