---
#These tasks install nginx
- name: Get installed modules for nginx
  shell: nginx -V
  register: nginx_flags
  ignore_errors: true

- set_fact:
    recompile: true
  when: "item not in nginx_flags.stderr"
  with_items: nginx_modules

- name: Download nginx from git
  git: repo={{item.repo}} dest={{item.dest}} version={{item.version}}
  with_items:
    - {
        repo: "https://github.com/nginx/nginx.git",
        dest: "nginx",
        version: $nginx_version
      }
  when: recompile == true

#- set_fact:
#    nginx_modules: ['--add-module=../modules/rtmp']
#  when: nginx_rtmp_module == true

- name: "Download nginx rtmp-module from git"
  git: repo={{item.repo}} dest={{item.dest}} version={{item.version}}
  with_items:
    - {
        repo: "https://github.com/arut/nginx-rtmp-module.git",
        dest: "modules/rtmp", version: $nginx_rtmp_module_version
      }
  when: nginx_rtmp_module == true and recompile == true

- name: Compile nginx
  command: chdir=nginx {{item}}
  with_items:
    - "./configure {{ nginx_modules|join(' ') }} --prefix=/opt/nginx"
    - "make -j4"
  when: recompile == true

- name: Install nginx
  sudo: true
  command: chdir=nginx make install
  when: recompile == true

- name: "Copy the nginx configuration file"
  sudo: true
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: "Copying nginx Shell script"
  sudo: true
  template: src=nginx dest=/etc/init.d/nginx mode=0711
  notify:
    - restart nginx
  when: recompile == true

- name: Create nginx directories for site configuration
  file: path=/etc/nginx/{{item}} state=directory owner=root group=root mode=0755
  sudo: yes
  with_items:
    - "sites-available"
    - "sites-enabled"

#- name: Add nginx default vhost
#  template: src=default dest=/etc/nginx/sites-available/default
#  sudo: yes
#  notify: 
#    - restart nginx

- name: Link nginx default vhost in sites-enabled
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
  sudo: yes
  notify:
    - restart nginx

- name: Add nginx $server_name vhost
  template: src=vhosts.dist dest=/etc/nginx/sites-available/{{ server_name }}
  sudo: yes
  notify: 
    - restart nginx

- name: Link nginx $server_name vhost in sites-enabled
  file: src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link
  sudo: yes
  notify:
    - restart nginx

- name: start the nginx service
  service: name=nginx state=started enabled=yes